# Tmux Nested
# from http://stahlke.org/dan/tmux-nested/

# go to nested tmux
bind -n M-S-up \
  set -q status "off" \; \
  set -q prefix C-b

# go to parent tmux
bind -n M-S-down \
  set -q status "on" \; \
  set -q prefix C-a
