
[env]
TERM = "xterm-256color"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Shift"

[keyboard]
bindings = [
  { key = "Q", mode = "Vi", action = "ToggleViMode" },
  { key = "Return", mods = "Shift", chars = "\u001b[13;2u" },
  { key = "Return", mods = "Control", chars = "\u001b[13;5u" },
]

[general]
import = ["~/.config/os-config/alacritty/alacritty.toml"]
