rules:
  indent:
    - warn
    - 2
  max-len:
    - warn
    - 80
  quotes:
    - warn
    - single
  linebreak-style:
    - error
    - unix
  no-unused-vars:
    - warn
  semi:
    - warn
    - always
env:
  es6: true
  node: true
  browser: true
extends: 'eslint:recommended'
ecmaFeatures:
  jsx: true
  experimentalObjectRestSpread: true
plugins:
  - react
